" =========================
"

" ------------------  Generic stuff
set nocompatible " do not act like vi
set background=dark

set nohlsearch   " only hilight search while typing it in
set incsearch    " hilight as long as pattern matches while typing
set smartcase    " ignorecase unless you use a capital letter, then case sensitive
set wildmenu     " status bar shows next matches
syntax enable    " syntax hilightning on
set laststatus=2

" turn line numbers on
set number
" highlight matching braces
set showmatch
" intelligent comments
set comments=sl:/*,mb:\ *,elx:\ */



filetype on      " determine file type and cause FileType event
filetype plugin on " load ftplugin.vim: filetype dependent plugins get loaded
filetype indent on " load ft dependent indent.vim ?

" set UTF-8 encoding
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

set backspace=2   " sane BS behaviour

" ------------------------   COLORSCHEMES
" colorscheme hse

" ------------------------------------------ indentation stuff
" use indentation of previous line
set autoindent
" use intelligent indentation for C
set smartindent
" configure tabwidth and insert spaces instead of tabs
set tabstop=4        " tab width is 4 spaces
set shiftwidth=4     " indent also with 4 spaces
set expandtab        " expand tabs to spaces
" indent when wrapping parameters
set cino=(0,g0

" wrap lines at 120 chars. 80 is somewhat antiquated with nowadays displays.
set textwidth=120
" tw +1 gets highlighted
set colorcolumn=+1
hi ColorColumn ctermbg=blue


" ------------ NETRW configuration
let g:netrw_liststyle = 3  " file browser layout
let g:netrw_banner = 0 " do not show banner
let g:netrw_browse_split =4 " open in old frame
let g:netrw_winsize = 25 " only 1/4 screen wide
let g:netrw_altv = 1 " dir stays left


" -------------------------- Header Files
" include guards
function! s:insert_gates()
  execute "normal! i#pragma once\<esc>o\<cr>"
endfunction

autocmd BufNewFile *.{h,hpp} call <SID>insert_gates()

:com -nargs=1 RT :!ctest -R <f-args> -V
:com -nargs=0 CM :!cmake ..
:com -nargs=1 T :!unixtime  <f-args>
:command! BW :bn|:bd#



let g:alternateExtensions_CPP = "inc,h,H,HPP,hpp"


" -------------- GIT stuff
" git commit
autocmd FileType gitcommit set tw=72
:com -nargs=0 GT :!git diff
:com -nargs=0 GL :!git log
:com -nargs=0 GS :!git status
:command! Gitdiff :!git diff
:command! Gitstatus :!git status

" ---------------------- CTRL-P -----------------
" fuzzy file search Ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_working_path_mode = 'ra'
" Exclude build dirs
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$\|mm$\|builddir$\|mvnbuild$\|target$' }

" ------------------------- FOLDING ----------------
" Folding
set foldmethod=syntax " indent
set foldlevelstart=20

:nnoremap __ :call RunTest()<CR>mT


" ---------- Function Key Assignments
map <F1> :Vexplore<CR>
map <F2> :!git diff <C-R>=expand('%')<CR><CR>
map <F3> :!git blame <C-R>=expand('%')<CR><CR>
map <F4> :call RunAllTestsInFile()<CR>
map <F5> :call RunAllTestsInSuite()<CR>
map <F8> :MM<CR>:RR<CR>
map <F9> zM
map <F10> zc
map <F11> zozz
map <F12> zR

nnoremap ,nt o<C-R>=AddNewTest()<CR><Esc>F,la



function! BufSel(pattern)
    let bufcount = bufnr("$")
    let currbufnr = 1
    let nummatches = 0
    let firstmatchingbufnr = 0
    while currbufnr <= bufcount
        if(bufexists(currbufnr))
            let currbufname = bufname(currbufnr)
            if(match(currbufname, a:pattern) > -1)
                echo currbufnr . ": ". bufname(currbufnr)
                let nummatches += 1
                let firstmatchingbufnr = currbufnr
            endif
        endif
        let currbufnr = currbufnr + 1
    endwhile
    if(nummatches == 1)
        execute ":buffer ". firstmatchingbufnr
    elseif(nummatches > 1)
        let desiredbufnr = input("Enter buffer number: ")
        if(strlen(desiredbufnr) != 0)
            execute ":buffer ". desiredbufnr
        endif
    else
        echo "No matching buffers"
    endif
endfunction

"Bind the BufSel() function to a user-command
command!  -nargs=1 Bs :call BufSel("<args>")
